### ISSUE TITLE
Consider Jitsi for OTR section

### ISSUE THREAD

**Issue by runasand** [freedomofpress/encryption-works#12]
I hear Jitsi is a good alternative to Pidgin, it even comes with OTR installed and enabled by default (I have not used this tool myself). This section should ideally explain that users should wait for the encrypted session to be established before saying anything more than "hi" or "ping". It would be helpful to mention alternative ways to exchange fingerprints, I hear some people use Twitter DMs for this purpose (whether that is something we want to recommend is something we should discuss).

**Comment by fowlslegs** [comment]
Going to close this because I believe we are moving to recommending Tor Messenger for the next versions. ZRTP apps could be easier to configure and are not nearly reliable enough in my experience to recommend right now, but I hope in the future we'll be able add such a section.
