### ISSUE TITLE
Allow readers to comment on individual paragraphs

### ISSUE THREAD

**Issue by runasand** [freedomofpress/encryption-works#15]
It would be great if Encryption Works was published in a way that would allow readers to comment on individual paragraphs, similar to what you see on medium.com.

**Comment by RichardLitt** [comment]
You can do that by referencing lines in a GitHub issue. [Example](https://github.com/freedomofpress/encryption-works/edit/master/encryption_works.md#L233)

**Comment by tommycollison** [comment]
I think comments are a good idea but referencing lines on Github/using Github at all requires an account and knowledge of how GH works. Do we want to limit commenting to these people?

**Comment by RichardLitt** [comment]
No, we don't. Another option would be to use Hypothes.is or Genius, or one of the other annotators out there. There's a learning curve there, too. Implementing an annotator just for this website is also possible. I think that the NYTimes has a plug and play annotator available in their repo by Donohue, or we could try plugging in Annotator.js. All of these options increase dev time, however, whereas GitHub is integrated into where the site is hosted. Some sort of GitHub annotator plugin would be great, but I don't know if that exists at the moment.

**Comment by conorsch** [comment]
From a maintenance standpoint, I think requiring remedial GitHub skills to suggest edits is fine for now. After all, the README lists contact information, including URLs and email addresses, in case someone wants to get in touch with us directly to recommend specific changes. In the unlikely event that we're swamped with edit suggestions via email, then we can look into rigging up an annotation framework and managing submissions in a more programmatic way.

**Comment by RichardLitt** [comment]
I agree that GitHub is a pretty low barrier to entry, all told.

**Comment by tommycollison** [comment]
@RichardLitt Yeah, that's true. I'm happy with GitHub, especially over Medium or a plugin.
