### ISSUE TITLE
Remove Micah Lee attribution from README

### ISSUE THREAD

**Issue by RichardLitt** [freedomofpress/encryption-works#193]
## Why

* It's not relevant to the README now that there are multiple contributors;
* The fingerprint is confusing if you're coming from freedom.press and just wanted to edit something (Is this a git hash? Should I update it? Etc.);
* It's presence suggests that the CC license above it should attribute Micah Lee, when I'm pretty sure it should instead be attributed to Freedom of the Press;
* The PGP key can quickly become outdated, and should point to a single point of truth (his website).

@micahflee is unambiguously the author of the original document, and we're working on updating how we credit people (see #186). However, his personal PGP fingerprint, twitter, and name don't really belong in the README.md. 

Issue instead of PR because this should clearly be discussed. I'm not trying to be an unkind bike shedder, I was just confused as to why it was there and I can't see a good enough reason except 'legacy' code.

**Comment by conorsch** [comment]
@RichardLitt Thanks for catching it! You're right, we talked extensively about attribution in the `encryption_works.md` document, but those changes have not percolated to the README yet—which is the landing page for folks viewing this repo.

As for resolution, I suggest moving the entire header from the Encryption Works document into the README:

> # Encryption Works
> ## A Guide to Protecting Your Privacy for Journalists, Sources, and Everyone Else

> *Dedicated to cypherpunks, and to whistleblowers past and future.*

> A publication of [Freedom of the Press Foundation](https://freedom.press/). Original version written by Micah Lee and published July 2013. Updated version written by Tommy Collison and published September 2015. Licensed as [Creative Commons Attribution 3.0 Unported](https://creativecommons.org/licenses/by/3.0/).

> If you're interested in contributing to Encryption Works, or have ideas for what this guide should cover, please check out the project on [GitHub](https://github.com/freedomofpress/encryption-works/blob/master/CONTRIBUTING.md).

>> Encryption works. Properly implemented strong crypto systems are one of the few things that you can rely on. Unfortunately, endpoint security is so terrifically weak that NSA can frequently find ways around it.
>> 
>>— Edward Snowden, answering questions live on the [Guardian's website](http://www.guardian.co.uk/world/2013/jun/17/edward-snowden-nsa-files-whistleblower).

@harlo Thoughts?

**Comment by RichardLitt** [comment]
Sounds smart to me. I wouldn't add in the third paragraph - we're already on GitHub. The Snowden quote helps the user understand why it is called "Encryption Works", so that should stay.

**Comment by fowlslegs** [comment]
Didn't see this before, but I asked @trevortimm about this and he suggested we put FPF contact info there since we maintain it ourselves now. Micah is still credited in encryption_works.md.

**Comment by RichardLitt** [comment]
Cool, thanks!
