### ISSUE TITLE
Password Managers - 1Password is not a 'browser extension'

### ISSUE THREAD

**Issue by grempe** [freedomofpress/encryption-works#238]
The document currently states:

'We recommend using KeePassX because it's open-source and a separate application (as opposed to a browser extension).'

1password is a stand-alone signed binary on OS X, iOS, Windows and Android. It *optionally* allows use of a helper application and browser extensions on the desktop.

https://agilebits.com/downloads

**Comment by gregoryhammond** [comment]
But the problem with 1password is you have to pay for it and it's not open source. Open source software allows everyone to see what is going on behind the scenes to make sure no third-parties have implemented anything into it.

**Comment by fowlslegs** [comment]
As @gregoryhammond pointed out this guide sticks to recommending open-source solutions (exceptions of course for operating systems and some of their core user programs). That said, we have been looking at other open-source alternatives to KeePassX, which have a more modern feel and perhaps even end-to-end encrypted cloud backups and synchronization like [Encryptr](https://spideroak.com/solutions/encryptr). If you have suggestions in this vein, please share. Closing this issue for now.
