### ISSUE TITLE
TLS is not especially "a protocol we can trust."

### ISSUE THREAD

**Issue by jdgalt** [freedomofpress/encryption-works#26]
<blockquote>That code, that's open and public so that fellow cypherpunks may practice and play with it, which anyone in the world can freely use, makes the basis of the software and protocols that we can trust: TLS (the encryption that powers HTTPS), LUKS (disk encryption built-in to GNU/Linux), OpenPGP, Off-the-Record, and Tor.</blockquote>

TLS, like the SSL it is derived from, suffers from a major problem: anyone designated as a "certificate authority" is capable of generating bogus certificates for any domain name in the world, allowing their possessors to impersonate that site in a way that most users and most browsers will never detect.  And the list of certificate authorities is huge, and includes nasty governments all over the world.

For a sampling of breaches this has already caused, go to
https://duckduckgo.com/?kh=1&q=certificate+authority&sites=www.schneier.com%2Fblog
and read the first 10 or 20 hits.

TLS really needs to be rebuilt from the ground up to use a PGP-like "web of trust" security model, and EFF has a project in progress now, "Sovereign Keys", that shows promise of doing this in the future.  But in the meantime, I suggest that we try to identify those CAs that we do need to trust and can trust, and publish it, so that people who need secure communications can disable all but those CAs in their browsers.  (In Firefox this setting is under Tools -> Options -> Advanced -> Certificates.)

**Comment by garrettr** [comment]
TLS and the CA PKI are orthogonal issues (although the CA PKI is commonly used to establish trust in software that uses TLS). The TLS protocol itself does not require the use of CA's, so the excerpt that you quoted is technically correct and I do not believe it needs to be changed.

Unfortunately, EFF is not working actively on Sovereign Keys anymore and it is unclear whether the proposed spec would've been effective anyway. Ideas from Sovereign Keys were incorporated into [Certificate Transparency](http://www.certificate-transparency.org/), which _is_ being actively developed and [meaningfully deployed](http://www.certificate-transparency.org/ev-ct-plan) at a global scale, so it is probably the best hope going forward to bolster our ability to trust encrypted communications that use the CA PKI to establish trust.
