### ISSUE TITLE
Add https://freedom.press/encryption-works to repository website field

### ISSUE THREAD

**Issue by RichardLitt** [freedomofpress/encryption-works#32]

**Comment by garrettr** [comment]
Sorry, I can't find the field you're talking about. Can you clarify?

**Comment by RichardLitt** [comment]
Sure!  Go to the main page for the repo, and click 'Edit' on the description. You can add the website there. Here is an example of what that looks like:

<img width="1093" alt="screen shot 2015-08-14 at 7 19 16 pm" src="https://cloud.githubusercontent.com/assets/910753/9285950/67810700-42b9-11e5-9e0b-24b4b6f8ca9e.png">

Make sense?

**Comment by garrettr** [comment]
D'oh! Thanks :sweat_smile:

**Comment by RichardLitt** [comment]
Np!
