### ISSUE TITLE
Fale sobre o ProtonMail

### ISSUE THREAD

**Issue by flanubio** [freedomofpress/encryption-works#35]
O que sabemos sobre este serviço de email? Podemos confiar?

**Comment by garrettr** [comment]
FPF hasn't evaluated ProtonMail yet, so we're not sure if we want to recommend it. See https://github.com/freedomofpress/encryption-works/pull/30#issuecomment-131214053 for more details.

**Comment by fowlslegs** [comment]
Since #30 is closed it makes sense to close this too. Also, unless ProtonMail moves to PGP (see [here](https://protonmail.com/support/knowledge-base/sending-a-message-using-pgppgp/)), we'd be encouraging people into a very tiny walled garden of encryption--not very practical.
