### ISSUE TITLE
Add 2 factor authentication

### ISSUE THREAD

**Issue by revswim** [freedomofpress/encryption-works#36]
I know the document is geared towards encryption rather than authentication but as you already have a small section on authentication in PGP and a section on creating secure passwords, could there also be a section on the various methods of 2 factor authentication and login? Sorry if this it too much trouble, I'm not an expert or a writer. I'd just be interested in learning about authenticators, key fobs, yubikey, cellphone authentication, etc so I'm just wishing for it. Mark me down for a +1 wish.

**Comment by garrettr** [comment]
@revswim We added a section about 2-factor authentication as part of the EW 2.0 rewrites, you can see it [here](https://github.com/freedomofpress/encryption-works/blob/master/encryption_works.md#two-factor-authentication-2fa). Is that sufficient to resolve this issue?

**Comment by RichardLitt** [comment]
The added section looks good to me, I would consider this resolved.

**Comment by conorsch** [comment]
@RichardLitt :+1: Glad to hear it!
