### ISSUE TITLE
Tails: Needs new screenshots.

### ISSUE THREAD

**Issue by tommycollison** [freedomofpress/encryption-works#37]
In the "Tails" section, the screenshots are for a previous version of the software. It should look something like: 
![screenshot from 2015-06-29 16_14_49](https://cloud.githubusercontent.com/assets/398046/8486565/752277d4-20d3-11e5-9fa0-cd1043fc2cc3.png)

**Comment by tommycollison** [comment]
I'm using Tails on a Mac, which may/may not be optimal?

**Comment by harlo** [comment]
Tails on a Mac has this horrible stretching effect.  It's not a deal-breaker per se, but if you're picky, it's not ideal for screenshotting.  There might be a way to fix the resolution, though, but I'm not sure.  Another thing to research...

**Comment by ageis** [comment]
In my experience with the SecureDrop documentation, running Tails in VirtualBox was the most convenient way to take screenshots.

**Comment by tommycollison** [comment]
Yeah, much better: 

![screen shot 2015-07-02 at 9 22 50 pm](https://cloud.githubusercontent.com/assets/398046/8490994/b41d71e6-2100-11e5-86f9-6849c216c5e4.png)

**Comment by garrettr** [comment]
@tommycollison @ageis FYI, it depends on your system. I usually also run Tails in Virtualbox to take screenshots. However, when I try to take screenshots with my Mac (e.g. using "Grab" or `Cmd-Shift-{3,4}`, I've had mixed results on my MBP with a Retina display. The graphics usually end up, as Harlo said, with this weird stretching effect that makes them take up a lot of space but still look very low res.

The solution for me was to take screenshots _inside_ Tails (with the Screenshot utility, I think you can also set up a keyboard shortcut for it but I haven't tried yet) and then transferring those out of Tails. It's not totally trivial to transfer those files out of Tails, but there are a number of different techniques that will work.

For me this produced high-quality screenshots with reasonable filesizes (< 150K for a `.png`).

FWIW, of course - the screenshot you [just posted](https://github.com/freedomofpress/encryption-works/issues/37#issuecomment-118207171) looks good to me.

**Comment by tommycollison** [comment]
@garrettr @ageis The [original](https://github.com/freedomofpress/encryption-works/issues/37#issue-92722982) stretched image I posted was a screenshot taken in Tails with the Screenshot utility and then transferred out. Unsure how to make it unstretched but VirtualBox may work for our screenshot purposes.
