### ISSUE TITLE
PGP: Change Screenshots To Two Different E-mails

### ISSUE THREAD

**Issue by tommycollison** [freedomofpress/encryption-works#42]
I think it's a little bit confusing to have the PGP images going back and forth between _micah@freedom.press_. Can we change them to go from one e-mail address to a different one?

![screen shot 2015-07-06 at 2 55 42 pm](https://cloud.githubusercontent.com/assets/398046/8530496/5162ae3a-23ef-11e5-8a90-356ef390521b.png)

**Comment by garrettr** [comment]
@tommycollison Was this fixed in one of your commits?

**Comment by tommycollison** [comment]
@garrettr Yep!
