### ISSUE TITLE
OTR: Add link to Intercept's OTR guide

### ISSUE THREAD

**Issue by tommycollison** [freedomofpress/encryption-works#69]
I'm unconvinced that _Encryption Works_ should include many how-tos, since these things go out of date pretty quickly. With that in mind, I'd like to pull out the section talking about what software to use with OTR and replace it with a link to The Intercept's guide to [Chatting In Secret While We're All Being Watched](https://firstlook.org/theintercept/2015/07/14/communicating-secret-watched/).

PR incoming.

**Comment by garrettr** [comment]
We discussed this and @tommycollison decided (after some review comments from @harlo) to leave mentions for specific software tools in EW, but to also link to the Intercept's new guide for secure chat.
